# ---------
# JEKYLL CONFIGURATION
# https://olivier3lanc.github.io/Jekyll-LibDoc/libdoc-config.html
# ---------

remote_theme: DouglasBrunner/Jekyll-LibDoc
title: Mail Minion
defaults:
  -
    values:
      layout: libdoc/page
kramdown:
    syntax_highlighter_opts:
        disable: true
sass:
    style: compressed

# METADATA
# Metadata informations for the site/project
metadata:
    # LANGUAGE
    # Change the language of the playground, default is en
    lang: en

    # CACHE
    # Enable or not browser cache for the playground
    cache: false

    # PNG favicon file 
    # Path from root or absolute/remote URL - Square 32x32 pixels icon png format or .ico for old browsers
    favicon: ""

    # THEME COLOR
    # Theme color metadata used in some browsers like Chrome that applies this color on browser address bar.
    # Color must be in HEX, default is LibDoc's color
    color: '#123456'

# SIDEBAR 
# Main navigation containing site/project's logo, pages links and search form.
sidebar:
    # SEARCH FEATURE
    # Enable or disable search feature
    disable_search: false

    # ADDITIONAL LINKS
    # Allows to add links that are not pages included into the project
    # Display additional links anywhere into the sidebar
    additional_links:
        -   url: https://github.com/DouglasBrunner/mail-minion
            title: <span class="i-github u-mr-xxs"></span> View on GitHub
            order: 0
            category: Project 

# SYNTAX HIGHLIGHTER / PRISM
# Settings for Prism syntax highlighter used in LibDoc
# https://prismjs.com/
prism:
    # THEME
    # coy, dark, funky, okaidia, twilight, solarizedlight, tomorrow, 
    theme: okaidia

    # FONT SIZE
    # CSS font-size property override for <code>
    font_size: 0.9em

    # LINE HEIGHT 
    # CSS line-height property override for <code>
    line_height: 1.4em

    # LANGUAGES TO ENABLE
    # Uncomment lines to enable language
    languages:
        - gherkin
        - java
        - javadoc
        - markdown
        - xml-doc
        - yaml