# ---------
# JEKYLL CONFIGURATION
# More info at https://jekyllrb.com/docs/configuration/options/
# ---------
# TO USE JEKYLL LIBDOC AS REMOTE THEME, UNCOMMENT (available only on Github)
remote_theme: DouglasBrunner/Jekyll-LibDoc
title: Mail Minion
# description: >- # Description of the docs. (>- means to ignore newlines until next param)
#   An automated helper to tackle email triage.
# IMPORTANT: on Github Pages deploys, url and baseurl must be commented or set to proper settings, otherwise links and resources URL are wrong
# url: http://localhost # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: /Jekyll-LibDoc/_site # the subpath of your site, e.g. /blog
#permalink: /:path/:basename/:output_ext
#destination: ../your/new/path # Build relative path destination. The destination directory e.g. /blog
#keep_files: [cache]
#markdown: kramdown
defaults:
  -
    values:
      layout: libdoc/page
kramdown:
    syntax_highlighter_opts:
        disable: true
sass:
    style: compressed
#exclude: ['/misc']

# ---------
# LIBDOC CONFIGURATION
# https://olivier3lanc.github.io/Jekyll-LibDoc/libdoc-config.html
# ---------

# PLAYGROUND
# The user context entirely separated from LibDoc theme
# playground:
#     # PLAYGROUND STYLESHEETS
#     # Style sheets in <head>. Can be either:
#     # Relative URL from site root starting with slash /
#     # Absolute URL starting with 'http'
#     stylesheets: 
#         - /demo-only/css/normalize.css
#         # - /demo-only/css/photoswipe.css
    
#     # PLAYGROUND HEAD JAVASCRIPTS
#     # Javascript in <head>. Can be either:
#     # Relative URL from site root starting with slash /
#     # Absolute URL starting with 'http'
#     scripts_head:
#         # - /assets/libdoc/js/my-toggles.js

#     # PLAYGROUND MODULES JAVASCRIPTS
#     # Javascript type="module" are set before text/javascript files
#     # JS modules do not work with a file:// URL 
#     # JS modules need a web server.
#     scripts_body_modules: 
#         # - /demo-only/js/demo.js

#     # PLAYGROUND BODY JAVASCRIPTS
#     # Javascript type="text/javascript" near </body>. Can be either:
#     # Relative URL from site root starting with slash /
#     # Absolute URL starting with 'http'
#     scripts_body: # Javascript files near </body>. Can be either relative URL from site root, absolute URL starting with 'http'
#         - /demo-only/js/ola.min.js
#         - /demo-only/js/scroll-btween.js
#         # - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js
#         # - /demo-only/js/demo.js
    
#     # PLAYGROUND MINIMUM HEIGHT
#     # Sets a minimum height for each playground, default is 300px
#     min_height: 300px

#     # PLAYGROUND METADATA
#     # Metadata for the playground only
#     metadata:
#         # PLAYGROUND LANGUAGE
#         # Change the language of the playground, default is en
#         lang: en

#         # PLAYGROUND CACHE
#         # Enable or not browser cache for the playground
#         cache: false
        
#         # PLAYGROUND PNG favicon file 
#         # Path from root or absolute/remote URL - Square 32x32 pixels icon png format or .ico for old browsers
#         favicon: /assets/libdoc/img/favicon/playground-android-chrome-512x512.png

#         # PLAYGROUND SVG favicon example - NOT supported on Safari
#         # favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%22256%22 height=%22256%22 viewBox=%220 0 100 100%22><rect width=%22100%22 height=%22100%22 rx=%2220%22 fill=%22%237d6ee7%22></rect><path fill=%22%23fff%22 d=%22M36.63 22.42L66.52 22.42Q66.78 22.87 67.06 23.63Q67.32 24.40 67.32 25.30L67.32 25.30Q67.32 26.83 66.60 27.73Q65.88 28.63 64.53 28.63L64.53 28.63L40.05 28.63L40.05 47.35L63.36 47.35Q63.63 47.80 63.91 48.56Q64.17 49.33 64.17 50.23L64.17 50.23Q64.17 51.76 63.45 52.66Q62.73 53.56 61.38 53.56L61.38 53.56L40.05 53.56L40.05 77.05Q39.60 77.23 38.66 77.41Q37.71 77.59 36.72 77.59L36.72 77.59Q32.67 77.59 32.67 74.34L32.67 74.34L32.67 26.38Q32.67 24.58 33.75 23.50Q34.84 22.42 36.63 22.42L36.63 22.42Z%22></path></svg>
        
#         # PLAYGROUND AUTOMATIC FAVICON 
#         # Automatic generation of multiple PNG favicons URL. Generates proper favicon files sizes for multiple devices. Must be an absolute URL starting with 'http'
#         # favicon_auto must be a public URL image file with a minimum 192x192 pixels 
#         # favicon_auto: https://i.ibb.co/cNmfL3D/android-chrome-512x512.png
        
#         # PLAYGROUND AUTHOR NAME
#         # Sets the name of the author for the playground. Default is empty.
#         author: 

#         # PLAYGROUND THEME COLOR
#         # Theme color metadata used in some browsers like Chrome that applies this color on browser address bar.
#         # Color must be in HEX, default is LibDoc's color
#         color: '#556e1e'

#         # PLAYGROUND IMAGE
#         # Open Graph image file for social networks. Can be either relative URL from site root, absolute URL starting with 'http'. Default is LibDoc's splash screen.
#         # image: /img/custom_image.webp
#         image: /assets/libdoc/img/meta-image-playground.jpg

# METADATA
# Metadata informations for the site/project
metadata:
    # LANGUAGE
    # Change the language of the playground, default is en
    lang: en

    # CACHE
    # Enable or not browser cache for the playground
    cache: false

    # PNG favicon file 
    # Path from root or absolute/remote URL - Square 32x32 pixels icon png format or .ico for old browsers
    # favicon: /assets/libdoc/img/favicon/favicon-32x32.png

    # SVG favicon example - NOT supported on Safari
    # favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%22256%22 height=%22256%22 viewBox=%220 0 100 100%22><rect width=%22100%22 height=%22100%22 rx=%2220%22 fill=%22%237d6ee7%22></rect><path fill=%22%23fff%22 d=%22M36.63 22.42L66.52 22.42Q66.78 22.87 67.06 23.63Q67.32 24.40 67.32 25.30L67.32 25.30Q67.32 26.83 66.60 27.73Q65.88 28.63 64.53 28.63L64.53 28.63L40.05 28.63L40.05 47.35L63.36 47.35Q63.63 47.80 63.91 48.56Q64.17 49.33 64.17 50.23L64.17 50.23Q64.17 51.76 63.45 52.66Q62.73 53.56 61.38 53.56L61.38 53.56L40.05 53.56L40.05 77.05Q39.60 77.23 38.66 77.41Q37.71 77.59 36.72 77.59L36.72 77.59Q32.67 77.59 32.67 74.34L32.67 74.34L32.67 26.38Q32.67 24.58 33.75 23.50Q34.84 22.42 36.63 22.42L36.63 22.42Z%22></path></svg>
    
    # AUTOMATIC FAVICON 
    # Automatic generation of multiple PNG favicons URL. Generates proper favicon files sizes for multiple devices. Must be an absolute URL starting with 'http'
    # favicon_auto must be a public URL image file with a minimum 192x192 pixels 
    # favicon_auto: https://i.ibb.co/cNmfL3D/android-chrome-512x512.png
    
    # AUTHOR NAME
    # Name of the author of the site/project, used into various places of the theme like footer. Default is empty
    author: 

    # THEME COLOR
    # Theme color metadata used in some browsers like Chrome that applies this color on browser address bar.
    # Color must be in HEX, default is LibDoc's color
    color: '#123456'

    # IMAGE
    # Open Graph image file for social networks. Can be either relative URL from site root, absolute URL starting with 'http'. Default is LibDoc's splash screen.
    # image: /img/custom_image.webp
    # image: /assets/libdoc/img/libdoc.png

# SIDEBAR 
# Main navigation containing site/project's logo, pages links and search form.
sidebar:
    # SEARCH FEATURE
    # Enable or disable search feature
    disable_search: false

    # LOGO
    # Top left branding/homepage link, specified image URL or site title if no URL is set
    # logo:
    #     # LOGO URL
    #     # Image URL: Can be local e.g. '/img/logo.png' or remote 'https://remotesite.com/img/logo.png'
    #     url: /assets/libdoc/img/favicon/android-chrome-512x512.png

    #     # LOGO MAX HEIGHT
    #     # Logo image max height, applies only if url is set
    #     max_height: 40px

    #     # LOGO FONT SIZE FALLBACK
    #     # If no logo url, font size of the site title, ignored if url is set
    #     font_size: 32px

    # ADDITIONAL LINKS
    # Allows to add links that are not pages included into the project
    # Display additional links anywhere into the sidebar
    additional_links:
        -   url: https://github.com/olivier3lanc/LibDoc-remote-demo # Local or remote URL
            title: <span class="i-github u-mr-xxs"></span> View on GitHub # Link text
            order: 0 # Sets the rank of the page link into the sidebar, higher values give lower rank for the page link
            # category: Showcase # Add this this link into a category just like pages

# SYNTAX HIGHLIGHTER / PRISM
# Settings for Prism syntax highlighter used in LibDoc
# https://prismjs.com/
prism:
    # THEME
    # coy, dark, funky, okaidia, twilight, solarizedlight, tomorrow, 
    theme: okaidia

    # FONT SIZE
    # CSS font-size property override for <code>
    font_size: 0.9em

    # LINE HEIGHT 
    # CSS line-height property override for <code>
    line_height: 1.4em

    # LANGUAGES TO ENABLE
    # Uncomment lines to enable language
    languages:
        - gherkin
        - java
        - javadoc
        - markdown
        - xml-doc
        - yaml

# LIBDOC BACKLINK
# Link powered by LibDoc - Uncomment to remove
# disable_powered_by_link: true