remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme

title: [Mail Minion]
description: [An automated helper to tackle email triage.]

collections:
  specification:
    output: true