remote_theme: DouglasBrunner/Jekyll-LibDoc
plugins:
- jekyll-remote-theme

title: [Mail Minion]
description: [An automated helper to tackle email triage.]

collections:
  specification:
    output: true

defaults:
  -
    values:
      layout: libdoc/page